In [12]:
import pandas as pd
from db import get_connection

conn = get_connection()

# Read read-only (CSV-backed) Lakehouse table
df = pd.read_sql(
    "SELECT * FROM dbo.data",
    conn
)

conn.close()

print(df.head())
print(df.shape)

C:\Users\shaiv.sud\AppData\Local\Temp\ipykernel_15112\3188231357.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(

   _c0  _c1 _c2       _c3   _c4  _c5      _c6      _c7    _c8      _c9   _c10  \
0  age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope
1   30    0   1       170   237    0        1      170      0        0      ?
2   36    1   3       112   340    0        0      184      0        1      2
3   37    1   4       120   223    0        0      168      0        0      ?
4   43    0   3       150     ?    0        0      175      0        0      ?

  _c11  _c12        _c13
0   ca  thal  num
1    ?     6           0
2    ?     3           0
3    ?     3           0
4    ?     3           0
(295, 14)

In [13]:
df.columns = [
    "age", "sex", "cp", "trestbps", "chol", "fbs",
    "restecg", "thalach", "exang", "oldpeak",
    "slope", "ca", "thal", "num"
]

In [14]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
1,30,0,1,170,237,0,1,170,0,0,?,?,6,0
2,36,1,3,112,340,0,0,184,0,1,2,?,3,0
3,37,1,4,120,223,0,0,168,0,0,?,?,3,0
4,43,0,3,150,?,0,0,175,0,0,?,?,3,0

In [15]:
# Replace '?' with NaN
df = df.replace("?", None)

# Convert columns to numeric
for col in df.columns:
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [16]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,30.0,0.0,1.0,170.0,237.0,0.0,1.0,170.0,0.0,0.0,NaN,NaN,6.0,0.0
2,36.0,1.0,3.0,112.0,340.0,0.0,0.0,184.0,0.0,1.0,2.0,NaN,3.0,0.0
3,37.0,1.0,4.0,120.0,223.0,0.0,0.0,168.0,0.0,0.0,NaN,NaN,3.0,0.0
4,43.0,0.0,3.0,150.0,NaN,0.0,0.0,175.0,0.0,0.0,NaN,NaN,3.0,0.0

In [17]:
df = df.iloc[1:].reset_index(drop=True)

In [18]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,30.0,0.0,1.0,170.0,237.0,0.0,1.0,170.0,0.0,0.0,NaN,NaN,6.0,0.0
1,36.0,1.0,3.0,112.0,340.0,0.0,0.0,184.0,0.0,1.0,2.0,NaN,3.0,0.0
2,37.0,1.0,4.0,120.0,223.0,0.0,0.0,168.0,0.0,0.0,NaN,NaN,3.0,0.0
3,43.0,0.0,3.0,150.0,NaN,0.0,0.0,175.0,0.0,0.0,NaN,NaN,3.0,0.0
4,46.0,1.0,4.0,110.0,238.0,0.0,1.0,140.0,1.0,1.0,2.0,NaN,3.0,0.0

In [19]:
df.shape

(294, 14)

In [22]:
new_row = {
    "age": 50.0,
    "sex": 1.0,
    "cp": 2.0,
    "trestbps": 140.0,
    "chol": 260.0,
    "fbs": 0.0,
    "restecg": 1.0,
    "thalach": 150.0,
    "exang": 0.0,
    "oldpeak": 1.5,
    "slope": 2.0,
    "ca": None,
    "thal": 3.0,
    "num": 1.0
}
df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)

C:\Users\shaiv.sud\AppData\Local\Temp\ipykernel_15112\1722472911.py:17: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)

In [23]:
df.shape

(295, 14)